require('dotenv').config();
const mongoose = require('mongoose');
const Medicine = require('./models/Medicine');

const URI = process.env.MONGO_URI || 'mongodb://localhost:27017/mediverse';

mongoose.connect(URI)
  .then(() => console.log('MongoDB Connected for Seeding'))
  .catch(err => {
    console.error(err);
    process.exit(1);
  });

const medicines = [
  // Pain Relief
  { name: 'Paracetamol 500mg', genericName: 'Acetaminophen', category: 'Pain Relief', manufacturer: 'PharmaCorp', description: 'Effective for fever and mild to moderate pain relief.', dosage: '1 tablet every 4-6 hours', price: 5.39, oldPrice: 5.99, discount: '10% OFF', rating: 4.8, reviews: 120, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Paracetamol 650mg', genericName: 'Acetaminophen', category: 'Pain Relief', manufacturer: 'PharmaCorp', description: 'Stronger dose for severe fever and body ache.', dosage: '1 tablet every 6-8 hours', price: 6.50, oldPrice: 7.00, discount: '7% OFF', rating: 4.7, reviews: 85, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Ibuprofen 400mg', genericName: 'Ibuprofen', category: 'Pain Relief', manufacturer: 'HealthPlus', description: 'Anti-inflammatory pain reliever for headaches and muscle aches.', dosage: '1 tablet every 6 hours with food', price: 6.50, oldPrice: 8.00, discount: '18% OFF', rating: 4.6, reviews: 90, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Ibuprofen 600mg', genericName: 'Ibuprofen', category: 'Pain Relief', manufacturer: 'HealthPlus', description: 'Higher strength anti-inflammatory for severe pain.', dosage: '1 tablet every 8 hours with food', price: 8.50, oldPrice: 10.00, discount: '15% OFF', rating: 4.5, reviews: 45, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Aspirin 75mg', genericName: 'Acetylsalicylic Acid', category: 'Pain Relief', manufacturer: 'CardioMed', description: 'Low dose aspirin for heart protection and mild pain.', dosage: '1 tablet daily', price: 4.99, oldPrice: null, discount: null, rating: 4.5, reviews: 200, stock: 'In Stock', prescriptionRequired: false, quantity: '14 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Diclofenac 50mg', genericName: 'Diclofenac Sodium', category: 'Pain Relief', manufacturer: 'ReliefPharma', description: 'For joint pain and severe inflammation.', dosage: '1 tablet twice a day', price: 7.20, oldPrice: 9.00, discount: '20% OFF', rating: 4.3, reviews: 65, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Aceclofenac 100mg', genericName: 'Aceclofenac', category: 'Pain Relief', manufacturer: 'MediPharm', description: 'Used for relief from pain and inflammation in rheumatoid arthritis.', dosage: '1 tablet twice a day', price: 6.00, oldPrice: 7.50, discount: '20% OFF', rating: 4.4, reviews: 55, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Naproxen 250mg', genericName: 'Naproxen', category: 'Pain Relief', manufacturer: 'PharmaCorp', description: 'Long-lasting relief from muscle pain and menstrual cramps.', dosage: '1 tablet twice a day', price: 8.50, oldPrice: 10.00, discount: '15% OFF', rating: 4.7, reviews: 110, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },

  // Antibiotics
  { name: 'Amoxicillin 250mg', genericName: 'Amoxicillin', category: 'Antibiotics', manufacturer: 'MediPharm', description: 'Treats bacterial infections such as pneumonia and bronchitis.', dosage: '1 capsule three times a day', price: 11.04, oldPrice: 12.99, discount: '15% OFF', rating: 4.7, reviews: 150, stock: 'In Stock', prescriptionRequired: true, quantity: '10 capsules', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Amoxicillin 500mg', genericName: 'Amoxicillin', category: 'Antibiotics', manufacturer: 'MediPharm', description: 'Higher strength for moderate to severe bacterial infections.', dosage: '1 capsule twice a day', price: 14.50, oldPrice: 16.00, discount: '9% OFF', rating: 4.8, reviews: 210, stock: 'In Stock', prescriptionRequired: true, quantity: '10 capsules', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Azithromycin 250mg', genericName: 'Azithromycin', category: 'Antibiotics', manufacturer: 'CureAll', description: 'Macrolide antibiotic for respiratory and skin infections.', dosage: '1 tablet daily for 5 days', price: 12.00, oldPrice: 14.00, discount: '14% OFF', rating: 4.6, reviews: 75, stock: 'In Stock', prescriptionRequired: true, quantity: '6 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Azithromycin 500mg', genericName: 'Azithromycin', category: 'Antibiotics', manufacturer: 'CureAll', description: 'Stronger macrolide antibiotic commonly prescribed as a Z-Pak.', dosage: '1 tablet daily for 3 days', price: 15.50, oldPrice: 18.00, discount: '13% OFF', rating: 4.9, reviews: 300, stock: 'In Stock', prescriptionRequired: true, quantity: '3 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Doxycycline 100mg', genericName: 'Doxycycline Hyclate', category: 'Antibiotics', manufacturer: 'HealthPlus', description: 'Tetracycline antibiotic for acne and bacterial infections.', dosage: '1 capsule twice a day', price: 12.00, oldPrice: 14.50, discount: '17% OFF', rating: 4.4, reviews: 110, stock: 'In Stock', prescriptionRequired: true, quantity: '10 capsules', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Cefixime 200mg', genericName: 'Cefixime', category: 'Antibiotics', manufacturer: 'MediPharm', description: 'Cephalosporin antibiotic for throat and ear infections.', dosage: '1 tablet twice a day', price: 13.50, oldPrice: 15.50, discount: '12% OFF', rating: 4.6, reviews: 90, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Ciprofloxacin 500mg', genericName: 'Ciprofloxacin', category: 'Antibiotics', manufacturer: 'PharmaCorp', description: 'Fluoroquinolone antibiotic for urinary tract infections.', dosage: '1 tablet twice a day', price: 14.00, oldPrice: 16.00, discount: '12% OFF', rating: 4.5, reviews: 140, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Metronidazole 400mg', genericName: 'Metronidazole', category: 'Antibiotics', manufacturer: 'CureAll', description: 'Treats bacterial and parasitic infections in the stomach and intestines.', dosage: '1 tablet three times a day', price: 9.00, oldPrice: 10.50, discount: '14% OFF', rating: 4.3, reviews: 85, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },

  // Vitamins
  { name: 'Vitamin D3 1000IU', genericName: 'Cholecalciferol', category: 'Vitamins', manufacturer: 'HealthPlus', description: 'Daily maintenance dose for bone and immune health.', dosage: '1 tablet daily', price: 8.54, oldPrice: 8.99, discount: '5% OFF', rating: 4.8, reviews: 450, stock: 'In Stock', prescriptionRequired: false, quantity: '30 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Vitamin D3 60000IU', genericName: 'Cholecalciferol', category: 'Vitamins', manufacturer: 'HealthPlus', description: 'High dose for treating Vitamin D deficiency.', dosage: '1 capsule weekly', price: 15.00, oldPrice: 18.00, discount: '16% OFF', rating: 4.9, reviews: 320, stock: 'In Stock', prescriptionRequired: true, quantity: '4 capsules', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Vitamin C 500mg', genericName: 'Ascorbic Acid', category: 'Vitamins', manufacturer: 'VitaLife', description: 'Chewable tablets for immunity boost.', dosage: '1 tablet daily', price: 9.99, oldPrice: 12.00, discount: '16% OFF', rating: 4.9, reviews: 500, stock: 'In Stock', prescriptionRequired: false, quantity: '30 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Vitamin C 1000mg', genericName: 'Ascorbic Acid', category: 'Vitamins', manufacturer: 'VitaLife', description: 'High strength immunity support and antioxidant.', dosage: '1 tablet daily', price: 14.50, oldPrice: 16.00, discount: '9% OFF', rating: 4.8, reviews: 250, stock: 'In Stock', prescriptionRequired: false, quantity: '20 effervescent tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Zinc Tablets', genericName: 'Zinc Gluconate', category: 'Vitamins', manufacturer: 'VitaLife', description: 'Essential mineral for immune function and metabolism.', dosage: '1 tablet daily', price: 6.50, oldPrice: 7.50, discount: '13% OFF', rating: 4.7, reviews: 180, stock: 'In Stock', prescriptionRequired: false, quantity: '30 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Multivitamin Capsules', genericName: 'Multivitamins & Minerals', category: 'Vitamins', manufacturer: 'NutriCare', description: 'Comprehensive daily multivitamin for overall wellbeing.', dosage: '1 capsule daily', price: 14.99, oldPrice: 19.99, discount: '25% OFF', rating: 4.6, reviews: 600, stock: 'In Stock', prescriptionRequired: false, quantity: '30 capsules', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Calcium Tablets', genericName: 'Calcium Carbonate', category: 'Vitamins', manufacturer: 'HealthPlus', description: 'Promotes strong bones and teeth.', dosage: '1 tablet twice a day', price: 10.00, oldPrice: 12.50, discount: '20% OFF', rating: 4.5, reviews: 210, stock: 'In Stock', prescriptionRequired: false, quantity: '30 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Iron Supplements', genericName: 'Ferrous Sulfate', category: 'Vitamins', manufacturer: 'VitaLife', description: 'Prevents and treats iron deficiency anemia.', dosage: '1 capsule daily', price: 8.50, oldPrice: 10.00, discount: '15% OFF', rating: 4.6, reviews: 150, stock: 'In Stock', prescriptionRequired: false, quantity: '30 capsules', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },

  // Heart Care
  { name: 'Atorvastatin 10mg', genericName: 'Atorvastatin Calcium', category: 'Heart Care', manufacturer: 'CardioMed', description: 'Lowers bad cholesterol and triglycerides in the blood.', dosage: '1 tablet daily at night', price: 22.50, oldPrice: 28.00, discount: '19% OFF', rating: 4.8, reviews: 340, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Atorvastatin 20mg', genericName: 'Atorvastatin Calcium', category: 'Heart Care', manufacturer: 'CardioMed', description: 'Higher dose for lowering cholesterol.', dosage: '1 tablet daily at night', price: 30.00, oldPrice: 35.00, discount: '14% OFF', rating: 4.7, reviews: 200, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Amlodipine 5mg', genericName: 'Amlodipine Besylate', category: 'Heart Care', manufacturer: 'HeartPharma', description: 'Treats high blood pressure and chest pain (angina).', dosage: '1 tablet daily', price: 15.00, oldPrice: 18.50, discount: '18% OFF', rating: 4.5, reviews: 180, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Amlodipine 10mg', genericName: 'Amlodipine Besylate', category: 'Heart Care', manufacturer: 'HeartPharma', description: 'Higher dose for high blood pressure control.', dosage: '1 tablet daily', price: 20.00, oldPrice: 24.00, discount: '16% OFF', rating: 4.6, reviews: 150, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Rosuvastatin 10mg', genericName: 'Rosuvastatin Calcium', category: 'Heart Care', manufacturer: 'HeartPharma', description: 'Statin medication to prevent cardiovascular disease.', dosage: '1 tablet daily', price: 24.00, oldPrice: 30.00, discount: '20% OFF', rating: 4.8, reviews: 260, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Telmisartan 40mg', genericName: 'Telmisartan', category: 'Heart Care', manufacturer: 'CardioMed', description: 'Angiotensin II receptor blocker for hypertension.', dosage: '1 tablet daily', price: 18.00, oldPrice: 20.00, discount: '10% OFF', rating: 4.6, reviews: 190, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Clopidogrel 75mg', genericName: 'Clopidogrel Bisulfate', category: 'Heart Care', manufacturer: 'PharmaCorp', description: 'Antiplatelet medication used to reduce the risk of heart disease and stroke.', dosage: '1 tablet daily', price: 20.00, oldPrice: 25.00, discount: '20% OFF', rating: 4.7, reviews: 140, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },

  // Diabetes
  { name: 'Metformin 500mg', genericName: 'Metformin HCl', category: 'Diabetes', manufacturer: 'DiabeCare', description: 'First-line medication for the treatment of type 2 diabetes.', dosage: '1 tablet twice a day with meals', price: 10.50, oldPrice: 12.00, discount: '12% OFF', rating: 4.7, reviews: 410, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Metformin 1000mg', genericName: 'Metformin HCl', category: 'Diabetes', manufacturer: 'DiabeCare', description: 'Extended release formulation for type 2 diabetes management.', dosage: '1 tablet daily with evening meal', price: 15.00, oldPrice: 18.00, discount: '16% OFF', rating: 4.6, reviews: 290, stock: 'In Stock', prescriptionRequired: true, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Glimepiride 2mg', genericName: 'Glimepiride', category: 'Diabetes', manufacturer: 'MediPharm', description: 'Stimulates insulin release from the pancreas.', dosage: '1 tablet before breakfast', price: 14.20, oldPrice: 17.00, discount: '16% OFF', rating: 4.6, reviews: 150, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Glimepiride 4mg', genericName: 'Glimepiride', category: 'Diabetes', manufacturer: 'MediPharm', description: 'Higher dose for blood sugar control.', dosage: '1 tablet before breakfast', price: 20.00, oldPrice: 23.00, discount: '13% OFF', rating: 4.5, reviews: 90, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Sitagliptin 50mg', genericName: 'Sitagliptin Phosphate', category: 'Diabetes', manufacturer: 'DiabeCare', description: 'DPP-4 inhibitor to improve glycemic control.', dosage: '1 tablet daily', price: 18.50, oldPrice: 22.00, discount: '15% OFF', rating: 4.8, reviews: 210, stock: 'In Stock', prescriptionRequired: true, quantity: '14 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Empagliflozin 10mg', genericName: 'Empagliflozin', category: 'Diabetes', manufacturer: 'DiabeCare', description: 'Helps the kidneys remove glucose from the bloodstream.', dosage: '1 tablet daily in the morning', price: 28.00, oldPrice: 35.00, discount: '20% OFF', rating: 4.7, reviews: 180, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Insulin Injection', genericName: 'Insulin Human', category: 'Diabetes', manufacturer: 'PharmaCorp', description: 'Short-acting insulin for blood sugar regulation.', dosage: 'As directed by physician', price: 35.00, oldPrice: 40.00, discount: '12% OFF', rating: 4.9, reviews: 120, stock: 'In Stock', prescriptionRequired: true, quantity: '1 vial (10ml)', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },

  // Cold & Flu
  { name: 'Cetirizine', genericName: 'Cetirizine HCl', category: 'Cold & Flu', manufacturer: 'ReliefPharma', description: 'Antihistamine for allergy symptoms and runny nose.', dosage: '1 tablet daily', price: 5.99, oldPrice: 7.50, discount: '20% OFF', rating: 4.5, reviews: 300, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Levocetirizine', genericName: 'Levocetirizine', category: 'Cold & Flu', manufacturer: 'PharmaCorp', description: 'Non-drowsy antihistamine for hay fever and hives.', dosage: '1 tablet daily in evening', price: 6.50, oldPrice: 8.00, discount: '18% OFF', rating: 4.6, reviews: 250, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Montelukast', genericName: 'Montelukast Sodium', category: 'Cold & Flu', manufacturer: 'ReliefPharma', description: 'Prevents wheezing and difficulty breathing caused by asthma.', dosage: '1 tablet daily in the evening', price: 12.00, oldPrice: 15.00, discount: '20% OFF', rating: 4.7, reviews: 190, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Sinarest', genericName: 'Paracetamol & CPM', category: 'Cold & Flu', manufacturer: 'HealthPlus', description: 'Multi-symptom relief for cold and sinus congestion.', dosage: '1 tablet every 6 hours', price: 7.50, oldPrice: 9.00, discount: '16% OFF', rating: 4.6, reviews: 400, stock: 'In Stock', prescriptionRequired: false, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Benadryl Syrup', genericName: 'Diphenhydramine', category: 'Cold & Flu', manufacturer: 'CureAll', description: 'Antihistamine cough syrup for allergy relief.', dosage: '1-2 teaspoons every 4-6 hours', price: 5.50, oldPrice: 6.50, discount: '15% OFF', rating: 4.4, reviews: 350, stock: 'In Stock', prescriptionRequired: false, quantity: '150ml bottle', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Cough Syrup', genericName: 'Dextromethorphan', category: 'Cold & Flu', manufacturer: 'CureAll', description: 'Soothes dry cough and throat irritation.', dosage: '10ml every 6 hours', price: 8.99, oldPrice: 10.00, discount: '10% OFF', rating: 4.3, reviews: 280, stock: 'In Stock', prescriptionRequired: false, quantity: '100ml bottle', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Steam Capsules', genericName: 'Camphor & Menthol', category: 'Cold & Flu', manufacturer: 'ReliefPharma', description: 'Inhalation capsules for immediate relief from nasal congestion.', dosage: '1 capsule in hot water for steam', price: 4.00, oldPrice: 5.00, discount: '20% OFF', rating: 4.5, reviews: 150, stock: 'In Stock', prescriptionRequired: false, quantity: '10 capsules', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },

  // Digestive Care
  { name: 'Pantoprazole 40mg', genericName: 'Pantoprazole Sodium', category: 'Digestive Care', manufacturer: 'GastroMed', description: 'Reduces stomach acid for acid reflux and ulcers.', dosage: '1 tablet before breakfast', price: 9.50, oldPrice: 12.00, discount: '20% OFF', rating: 4.7, reviews: 420, stock: 'In Stock', prescriptionRequired: true, quantity: '10 tablets', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Omeprazole 20mg', genericName: 'Omeprazole', category: 'Digestive Care', manufacturer: 'HealthPlus', description: 'Proton pump inhibitor to decrease acid production.', dosage: '1 capsule before meals', price: 8.00, oldPrice: 10.50, discount: '23% OFF', rating: 4.6, reviews: 380, stock: 'In Stock', prescriptionRequired: true, quantity: '15 capsules', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Digene', genericName: 'Antacid Gel', category: 'Digestive Care', manufacturer: 'GastroMed', description: 'Fast relief from acidity and gas.', dosage: '2 tablets chewed after meals', price: 5.50, oldPrice: 6.50, discount: '15% OFF', rating: 4.8, reviews: 500, stock: 'In Stock', prescriptionRequired: false, quantity: '15 tablets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'ORS Powder', genericName: 'Oral Rehydration Salts', category: 'Digestive Care', manufacturer: 'VitaLife', description: 'Restores body fluids and electrolytes lost due to dehydration.', dosage: 'Dissolve 1 sachet in 1 liter of water', price: 2.99, oldPrice: 3.50, discount: '14% OFF', rating: 4.9, reviews: 600, stock: 'In Stock', prescriptionRequired: false, quantity: '5 sachets', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Lactulose Syrup', genericName: 'Lactulose Solution', category: 'Digestive Care', manufacturer: 'GastroMed', description: 'Laxative to treat chronic constipation.', dosage: '15-30ml daily as prescribed', price: 12.00, oldPrice: 15.00, discount: '20% OFF', rating: 4.5, reviews: 220, stock: 'In Stock', prescriptionRequired: false, quantity: '200ml bottle', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Antacid Suspension', genericName: 'Magnesium & Aluminium Hydroxide', category: 'Digestive Care', manufacturer: 'HealthPlus', description: 'Liquid antacid for rapid heartburn relief.', dosage: '1-2 teaspoons after meals', price: 6.50, oldPrice: 8.00, discount: '18% OFF', rating: 4.4, reviews: 180, stock: 'In Stock', prescriptionRequired: false, quantity: '170ml bottle', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },

  // Skin Care
  { name: 'Calamine Lotion', genericName: 'Calamine', category: 'Skin Care', manufacturer: 'DermaCare', description: 'Soothing lotion for sunburns, bug bites, and skin irritation.', dosage: 'Apply topically as needed', price: 8.50, oldPrice: 10.00, discount: '15% OFF', rating: 4.6, reviews: 310, stock: 'In Stock', prescriptionRequired: false, quantity: '100ml bottle', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },
  { name: 'Antifungal Cream', genericName: 'Clotrimazole', category: 'Skin Care', manufacturer: 'SkinHealth', description: 'Treats fungal skin infections like athlete\'s foot and ringworm.', dosage: 'Apply thin layer twice daily', price: 6.00, oldPrice: 7.50, discount: '20% OFF', rating: 4.5, reviews: 240, stock: 'In Stock', prescriptionRequired: false, quantity: '15g tube', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Hydrocortisone Cream', genericName: 'Hydrocortisone', category: 'Skin Care', manufacturer: 'SkinHealth', description: 'Reduces swelling, itching, and redness in dermatitis and eczema.', dosage: 'Apply small amount 1-2 times daily', price: 9.50, oldPrice: 11.00, discount: '13% OFF', rating: 4.7, reviews: 190, stock: 'In Stock', prescriptionRequired: true, quantity: '10g tube', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Moisturizer', genericName: 'Aloe Vera & Vitamin E', category: 'Skin Care', manufacturer: 'DermaCare', description: 'Daily hydrating cream for soft and supple skin.', dosage: 'Apply generously over body', price: 15.00, oldPrice: 18.00, discount: '16% OFF', rating: 4.8, reviews: 450, stock: 'In Stock', prescriptionRequired: false, quantity: '200g jar', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'Sunscreen SPF 50', genericName: 'Zinc Oxide', category: 'Skin Care', manufacturer: 'SkinHealth', description: 'Broad-spectrum protection against UVA and UVB rays.', dosage: 'Apply 15 minutes before sun exposure', price: 20.00, oldPrice: 25.00, discount: '20% OFF', rating: 4.7, reviews: 520, stock: 'In Stock', prescriptionRequired: false, quantity: '50ml tube', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' },

  // Children's Care
  { name: 'Paracetamol Syrup', genericName: 'Acetaminophen', category: "Children's Care", manufacturer: 'PharmaCorp', description: 'Fever and pain relief specially formulated for kids.', dosage: 'As per body weight every 6 hours', price: 6.50, oldPrice: 8.00, discount: '18% OFF', rating: 4.7, reviews: 380, stock: 'In Stock', prescriptionRequired: false, quantity: '60ml bottle', image: 'https://images.unsplash.com/photo-1550572017-edb79998858d?w=400&q=80' },
  { name: 'Vitamin Gummies', genericName: 'Multivitamins', category: "Children's Care", manufacturer: 'NutriCare', description: 'Tasty gummy vitamins for growing kids.', dosage: '1 gummy daily', price: 12.00, oldPrice: 15.00, discount: '20% OFF', rating: 4.9, reviews: 450, stock: 'In Stock', prescriptionRequired: false, quantity: '30 gummies', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80' },
  { name: 'Children\'s Cough Syrup', genericName: 'Dextromethorphan', category: "Children's Care", manufacturer: 'CureAll', description: 'Soothes children\'s coughs without drowsiness.', dosage: '5ml every 6-8 hours', price: 7.99, oldPrice: 9.50, discount: '15% OFF', rating: 4.5, reviews: 290, stock: 'In Stock', prescriptionRequired: false, quantity: '100ml bottle', image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&q=80' },
  { name: 'ORS Sachets', genericName: 'Oral Rehydration Salts', category: "Children's Care", manufacturer: 'VitaLife', description: 'Apple flavored hydration salts for children.', dosage: 'Mix 1 sachet in 200ml water', price: 4.50, oldPrice: 5.50, discount: '18% OFF', rating: 4.8, reviews: 150, stock: 'In Stock', prescriptionRequired: false, quantity: '10 sachets', image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80' }
];

const seedDB = async () => {
  try {
    const count = await Medicine.countDocuments();
    if (count === 0) {
      console.log('Seeding medicines...');
      await Medicine.insertMany(medicines);
      console.log('Successfully added 50+ medicines.');
    } else {
      console.log('Medicines collection is not empty, skipping seeding.');
    }
    // We only close connection if we run this as a standalone script
    if (require.main === module) {
      mongoose.connection.close();
    }
  } catch (error) {
    console.error('Error seeding DB:', error);
    if (require.main === module) {
      mongoose.connection.close();
    }
  }
};

if (require.main === module) {
  seedDB();
}

module.exports = seedDB;
